spring:
  profiles:
    active: local
  application:
    name: peng-code-generation-platform
  mvc:
    async:
      request-timeout: 300000
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

server:
  port: 8123
  servlet:
    context-path: /api
  tomcat:
    connection-timeout: 300000

# springdoc-openapi
springdoc:
  group-configs:
    - group: 'default'
      packages-to-scan: com.peng.codegenerationplatform.controller
# knife4j
knife4j:
  enable: true
  setting:
    language: zh_cn


